### ISSUE TITLE
[A2] - Linha 2014 (PDF's em branco)

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/pdf-maker#2]
Olá, reparei que os dois PDF's da linha 2014, nomeadamente nas paragens `070331` e `071599`, encontram-se totalmente em branco!

https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-2014-0-070331.pdf

https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-2014-1-071599.pdf

**Comment by ttmx** [comment]
A investigar!

**Comment by ttmx** [comment]
Está resolvido! Eventualmente os pdfs estarão corrigidos no site.
Se houver curiosidade, o código assumia a existência de pelo menos 3 paragens, uma de inicio, um "corpo", e uma de fim.
Muito obrigado pelo feedback! 
[timetable-2014-1-071599.pdf](https://github.com/carrismetropolitana/pdf-maker/files/15375561/timetable-2014-1-071599.pdf)
[timetable-2014-0-070331.pdf](https://github.com/carrismetropolitana/pdf-maker/files/15375560/timetable-2014-0-070331.pdf)

**Comment by stgarmm** [comment]
Obrigado pela resolução, @ttmx!
