### ISSUE TITLE
[A1] - Pdf's da linha 1998 (CP) em branco

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/pdf-maker#5]
Olá, reprei que os Pdf's da linha 1998 (CP) estão em branco, tanto na `1998_0` como na `1998_1`, seguem abaixo os respetivos pdf's

**`1998_0`**
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-0-050010.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-0-050022.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-0-050036.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-0-050044.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-0-050045.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-0-050050.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-0-050052.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-0-120729.pdf

**`1998_1`**
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-1-050006.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-1-050008.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-1-050018.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-1-050042.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-1-050044.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-1-050048.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-1-050050.pdf
https://storage.carrismetropolitana.pt/static/pdfs/horarios/timetable-1998-1-050052.pdf

**Comment by ttmx** [comment]
Alô, obrigado pelo report, vou ver o que se passa!
